version: chm-{build}

environment:
  matrix:
    - CHECKOUTDIR: '%TEMP%\ags-manual.wiki'
      HHC: '%PROGRAMFILES(X86)%\HTML Help Workshop\hhc.exe'
      PANDOCVERSION: 2.7.3

branches:
  except:
    - gh-pages

install:
  - cinst pandoc --version %PANDOCVERSION%
  - cinst html-help-workshop make

before_build:
  - '%COMSPEC% /c "cd %TEMP% && git clone https://github.com/adventuregamestudio/ags-manual.wiki.git"'

build_script:
  - make SHELL=%COMSPEC% source
  - make SHELL=%COMSPEC% -j %NUMBER_OF_PROCESSORS% metacheck 2>&1 >nul | findstr /r . && exit 1 & exit 0
  - make SHELL=%COMSPEC% -j %NUMBER_OF_PROCESSORS% htmlhelp

artifacts:
- path: htmlhelp\build\ags-help.chm
  name: ags-help.chm

deploy:
- provider: GitHub
  auth_token:
    secure: RE/XSZF5WYBi1os9XeUernSQ7znWyIeCUu5m8rzCR/Ocyhmcjoa4N2101UXxtRPr
  artifact: ags-help.chm
  draft: false
  prerelease: false
  on:
    branch: master                 # release from master branch only
    appveyor_repo_tag: true        # deploy on tag push only
